version: '3.8'

services:
  db:
    image: postgres:15
    container_name: onepiece-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: onepiece
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: onepiecedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
