
services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_opex
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: one_piece
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_opex
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/one_piece"
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && node src/server.js" #&& npx prisma db seed

volumes:
  postgres_data:
